# Generated by Django 4.1 on 2022-08-31 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0002_initial'),
        ('category_app', '0002_alter_tag_options_alter_tag_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(default=2022, verbose_name='Year')),
                ('country', models.CharField(max_length=10, verbose_name='Country')),
                ('price', models.PositiveIntegerField(default=0, help_text='Indicate the amount in Belarusian rubles', verbose_name='Price')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_app.mediafile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category_app.tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_post', models.ImageField(blank=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.post')),
            ],
        ),
    ]
