# Generated by Django 4.1 on 2022-09-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_post', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(default=2022, verbose_name='Year')),
                ('country', models.CharField(max_length=10, verbose_name='Country')),
                ('price', models.PositiveIntegerField(default=0, help_text='Indicate the amount in Belarusian rubles', verbose_name='Price')),
            ],
        ),
    ]
