# Generated by Django 4.1 on 2022-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
