# Generated by Django 4.1 on 2022-09-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_post_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_visit',
        ),
    ]
