# Generated by Django 4.1 on 2022-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Indicate the amount in Belarusian rubles', verbose_name='Price'),
        ),
    ]
