# Generated by Django 4.1 on 2022-09-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0002_favoriteproduct_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='confirmation',
        ),
    ]
