# Generated by Django 4.1 on 2022-09-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_review', models.ImageField(blank=True, upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_app.review')),
            ],
        ),
    ]
