# Generated by Django 4.1 on 2022-09-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
