# Generated by Django 4.1 on 2022-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
