# Generated by Django 4.1 on 2022-09-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_review_ip_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rating']},
        ),
    ]
