# Generated by Django 4.1 on 2022-09-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
