# Generated by Django 4.1 on 2022-09-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_initial'),
        ('review_app', '0004_alter_review_post_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_app.mediafile'),
        ),
    ]
