# Generated by Django 4.1 on 2022-09-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0005_review_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='file',
        ),
        migrations.AlterField(
            model_name='mediareview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='review_app.review'),
        ),
    ]
