# Generated by Django 4.1 on 2022-09-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0006_remove_review_file_alter_mediareview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediareview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='review_app.review'),
        ),
    ]
